import Head from "next/head";
import { ReactNode } from "react";

import styles from "@/styles/DefaultLayout.module.css";

export const DefaultLayout = ({ children }: { children?: ReactNode }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>{children}</main>
    </>
  );
};
